import Head from 'next/head';
import Link from "next/link";
import { useState } from 'react';
import { Button, Center, HStack } from '@chakra-ui/react'
import { Grid, GridItem } from '@chakra-ui/react'

import Navbar from '../components/Navbar';
import Post from '../components/PostCard';
import Footer from '../components/Footer';


export default function Posts({ posts }) {

    return <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Grid templateColumns='repeat(4, 1fr)' gap={4}>
      {posts.map(post => (<Post key={post.id} post={post}  />))}
      </Grid>
      <Footer />
      </>;
  };

  
export async function getServerSideProps(context) {
  const posts = await fetch(`https://gorest.co.in/public/v2/posts`)
    .then(response => response.json());
  
  return { props: { posts } };
};
