import Head from 'next/head';
import Link from "next/link";
import { useState } from 'react';
import { Button, Center, HStack, Grid } from '@chakra-ui/react'
import { PhoneIcon, AddIcon, WarningIcon } from '@chakra-ui/icons'

import Navbar from '../components/Navbar';
import User from '../components/UserCard';
import Footer from '../components/Footer';


export default function Users({ users }) {
  
  const totalPages = users.meta.pagination.pages;
  const[currentPage, setCurrentPage] = useState(1);

  const nextPage = () => {
    if(currentPage <= totalPages && currentPage !== totalPages){
      setCurrentPage(currentPage + 1);
    };
  };

  const previousPage = () => {
    if(currentPage > 0 && currentPage !== 1){
      setCurrentPage(currentPage - 1);
    };
  };

  return <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={<PhoneIcon />} />
      </Head>
      <Navbar />
      <main>
      <Grid templateColumns='repeat(6, 1fr)' gap={1}>
          {users.data.map(user => (<User key={user.id} user={user}/>))} 
      </ Grid >
        
        <Center h="80px"><HStack spacing="40px">
          <Button onClick={() => previousPage()} >
            <Link href={`/users?page=${currentPage}`} passHref>Previous Page</Link>
          </Button>
          <Button onClick={() => nextPage()}  >
            <Link href={`/users?page=${currentPage}`} passHref>Next Page</Link>
          </Button> 
        </HStack></Center>
        <Footer />
      </main>
    </>;
};

export async function getServerSideProps(context) {
 
  const res = await fetch(`https://gorest.co.in/public/v1/users${"?page="+context.query.page || ""}`);
  const users = await res.json();

  return { props: { users } };
};