import Head from 'next/head';
import Link from "next/link";
import { useState } from 'react';
import { Button, Center, HStack } from '@chakra-ui/react'

import Navbar from '../components/Navbar';
import TableOfUsers from '../components/TableOfUsers';


export default function Users({ users }) {
  
  const totalPages = users.meta.pagination.pages;
  const[currentPage, setCurrentPage] = useState(1);

  const nextPage = () => {
    if(currentPage <= totalPages && currentPage !== totalPages){
      setCurrentPage(currentPage + 1);
    };
  };

  const previousPage = () => {
    if(currentPage > 0 && currentPage !== 1){
      setCurrentPage(currentPage - 1);
    };
  };

  return <>
      <Head>
        <title>Usuários</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <TableOfUsers users={users.data} />
        <Center h="80px"><HStack spacing="40px">
          <Button onClick={() => previousPage()} >
            <Link href={`/users?page=${currentPage}`} passHref>Página Anterior</Link>
          </Button>
          <Button onClick={() => nextPage()}  >
            <Link href={`/users?page=${currentPage}`} passHref>Próxima Página</Link>
          </Button> 
        </HStack></Center>
      </main>
    </>;
};

export async function getServerSideProps(context) {
 
  const res = await fetch(`https://gorest.co.in/public/v1/users${"?page="+context.query.page || ""}`);
  const users = await res.json();

  return { props: { users } };
};